
coverage:
  status:
    project:
      default:
        # basic
        target: 95%
        threshold: 0.5%
        # advanced settings
        branches:
          - main
          - dev
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false
    patch:
      default:
        # basic
        target: 95%
        threshold: 0.5%
        branches:
          - main
          - dev
        if_ci_failed: error #success, failure, error, ignore
        informational: false
        only_pulls: false